### PR TITLE
Performance issues

### PR DESCRIPTION
**Pull request by dy**
Regarding #5, so there are enhancements to `fillRect`, `clearRect` methods. It appears that simple 2d walkers almost a couple of orders faster than similar matrix operations.
Also there is `strokeRect` method, and a stub for `toString`. Guess it is never bad to have `toString` implemented).
All that moves package a step forward towards plotting graphs in terminal ). The rest is up to colors and text.
@madbence

### CODE REVIEW

**Comment by madbence** [comment]
afaik this will ignore the transformation matrix :confused: or am i missing something?

**Comment by dy** [comment]
@madbence you’re right, I missed it. It seems to be difficult then

**Comment by madbence** [comment]
In order to solve this, we have to do some manual clipping and polygon triangulation :crying_cat_face:

**Comment by dy** [comment]
@madbence performance metrics show that the bottleneck is not matrix, it is `triangle` method. Keep digging...)

**Comment by dy** [comment]
@madbence modified `quad` and `triangle` methods take clipping argument, that only affects the triangle walker, which now ignores all points with `y` outside of the clipping area and limits `x` lines by the width of clipping area. It was the most serious bottleneck.

**Comment by dy** [comment]
@madbence so what do you think? I’ve tested it on different matrix transforms - it seems to work good.

**Comment by madbence** [comment]
lgtm! :+1: awesome work

**Comment by dy** [comment]
Great :sunglasses:!

**Pull request merged**
