### PR TITLE
Drawille@1.1.0

### PR DESCRIPTION
**Pull request by dy**
Just use latest drawille.
@madbence

### CODE REVIEW

**Comment by ada-lovecraft** [comment]
+1

Also: it's incredibly crazy. I'm working with stuff from @dfcreative right now (trying to load a local audio file, do some analysis, and control some external LEDs/Hue Lights on kick/snare). Work from both @dfcreative and @madbence have been popping up all over the place in my code today.

**Comment by dy** [comment]
@codevinsky wow, hope it works, as it is pretty much WIP right now, all the modules from the [audio-lab](https://github.com/audio-lab). The dream is to come up with writing tracks via code and mastering via unix-pipes :laughing:

**Comment by ada-lovecraft** [comment]
If i understood, what seems to be, the very simple act of just grabbing waveform and frequency data, and not visualization, from a readable stream, I'd already be done :P

**Comment by dy** [comment]
Well I am very glad if it helps you in any way )

**Comment by ada-lovecraft** [comment]
It has been an incredible help. node-web-audio-api seems to have gone unmaintained before they implemented the AnalyserNode API. audio-lab has been fantastic thus far.

**Comment by dy** [comment]
Yes, all the story behind the web-audio-api in general is quite frustrating, as far we cannot do mixer node (or any node with multiple inputs in general), until there is no audio-workers. But there is already nice mechanism of pcm-streams, introduced by @tootallnate in [speaker](https://www.npmjs.com/package/speaker), @mmckegg in [livejs](https://github.com/livejs), @substack in [baudio](https://www.npmjs.com/package/baudio) etc etc, which is able to be easily conneced to web-audio-api, through [audio-buffer-stream](https://www.npmjs.com/package/audio-buffer-stream), [audio-speaker](https://www.npmjs.com/package/audio-speaker) and alike. PCM-streams work well both in browser/node. And it is easy and fun.

@madbence sorry for extensive offtop)

**Comment by madbence** [comment]
lgtm :+1: thank you :heart_eyes: i'm not sure if what release should this be (imho maybe minor?)

**Pull request merged**
