### PR TITLE
Make API a bit more compatible with browserify

### PR DESCRIPTION
**Pull request by dy**
Hi!
There is a couple of small improvements which make node-drawille easier to use with browserify. Now for browser there is a simple stub for real canvas, basically:

``` js
var Canvas = require('drawille-canvas');
var canvas = new Canvas(w,h);
if (isBrowser) document.body.appendChild(canvas);
var context = canvas.getContext('2d');

//do everything with context as usual
context.fillRect(0,0,10,10);
```

So now it is possible to just `require('drawille-canvas')` with no worries for browser/node.

There is a question for node still, what to do with `canvas._canvas.frame()`. Some alternate to `document.appendChild(canvas)` would be just perfect, but I can’t come up with anything interesting. Maybe something like `canvas.pipe(process.stdout)`?

And btw, please set package version to 1.0.0 - it will make easier to update)

### CODE REVIEW

**Comment by dy** [comment]
@madbence what prevents you from merging it :)?

**Comment by madbence** [comment]
nothing, i just did't had time to read it :smile: looks great!

**Comment by dy** [comment]
Wee)

**Comment by dy** [comment]
@madbence Can you also `npm version major && npm publish` pls))

**Comment by dy** [comment]
@madbence or add me as `$ npm owner add dfcreative drawille-canvas`, I’ll do the routine

**Comment by madbence** [comment]
sure, `drawille-canvas@1.0.0` published, i've added you as npm owner too, sorry for the delay :smile_cat: . Feel free to improve the package, just keep this pull-request workflow :heart:

**Comment by dy** [comment]
:heartpulse::innocent:

**Pull request merged**
